apiVersion: integration/v1
kind: Trigger
name: victorops-trigger-incident-triggered
version: 1
summary: VictorOps incident triggered
description: |
  This trigger fires when a VictorOps incident is triggered for the first time.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker
