apiVersion: container/v1
kind: StepContainer
name: victorops-trigger-incident-triggered
inherit: {from: sdk, name: python.v1}
title: VictorOps incident triggered
description: >
  This trigger fires when a VictorOps incident is triggered for the first time.
settings:
  CommandPath: handler.py
  AdditionalPythonPackages:
  - quart
